imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%.log'
            level: error
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
