flover_apps:
    resource: "@FloverAppsBundle/Resources/config/routing.yml"
    prefix:   /apps

floverart:
    resource: "@FloverartBundle/Resources/config/routing.yml"
    prefix:   /v1

floverart_login:
    resource: "@FloverartBundle/Resources/config/login.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
