# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

#    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider_floverart:
            entity:
                class: FloverartBundle:Users
                property: id

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/v1
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - user_provider_floverart

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~