services:
    floverart_api.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments: [[
            '@floverart_api.normalizer.users',
            '@floverart_api.normalizer.orders',
            '@floverart_api.normalizer.ship',
            '@floverart_api.constraint.violation',
            ], ['@floverart_api.encoder.json']]

    floverart_api.normalizer.users:
        class: FloverartBundle\Serializer\UsersNormalizer

    floverart_api.normalizer.orders:
        class: FloverartBundle\Serializer\OrdersNormalizer

    floverart_api.normalizer.ship:
        class: FloverartBundle\Serializer\ShipNormalizer

    floverart_api.constraint.violation:
        class: FloverartBundle\Serializer\ConstraintViolationNormalizer

    floverart_api.encoder.json:
        class: \Symfony\Component\Serializer\Encoder\JsonEncoder

    user_provider_floverart:
        class: FloverartBundle\Security\TokenAuthenticator