<?php

namespace FloverartBundle\Repository;

/**
 * CatalogFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogFilesRepository extends \Doctrine\ORM\EntityRepository
{
}
