<?php

namespace FloverartBundle\Repository;

use FloverartBundle\Entity\Clients;

/**
 * ClientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsRepository extends \Doctrine\ORM\EntityRepository
{
    const SALT = '?~*W3P~4z8Ef57#c}eV50~qb8av#qqK|9giJtgdB';

    public function validateToken($token) {
        list($rnd, $hash, $clientId) = explode('.', $token);

        if (empty($rnd) || empty($hash) || empty($clientId)) {
            return false;
        }

        return sha1($rnd . self::SALT . $clientId) == $hash;
    }

    public function generateToken(Clients $client, $rnd)
    {
        $hash = sha1(  $rnd . self::SALT . $client->getId());

        $token = [
            $rnd,
            $hash,
            $client->getId()
        ];

        return implode('.' , $token);
    }

    public function getClientByToken($token) {
        list($rnd, $hash, $clientId) = explode('.', $token);

        return $this->find($clientId);
    }
}
