<?php

namespace FloverartBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $filter
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getOrdersQuery($filter) {
        $q = $this->createQueryBuilder("p")
            ->orderBy('p.id','DESC');

        if (isset($filter['client_id'])) {
            $q->andWhere('p.clientId = :clientId')
                ->setParameter('clientId', (int)$filter['client_id']);
        }

        return $q;
    }

    /**
     * @param $orders
     * @param $ships
     *
     * @return mixed
     */
    public function joinShips($orders, $ships) {
        if (!$orders || !$ships) {
            return $orders;
        }

        foreach ($orders as $index => $order) {
            if (isset($ships[$order->getShippingId()])) {
                $orders[$index]->setShip($ships[$order->getShippingId()]);
            }
        }

        return $orders;
    }
}
