<?php

namespace FloverartBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrdersQuery($filter) {
        $q = $this->createQueryBuilder("p")
            ->orderBy('p.id','DESC');

        if (isset($filter['client_id'])) {
            $q->andWhere('p.clientId = :clientId')
                ->setParameter('clientId', (int)$filter['client_id']);
        }

        return $q;
    }
}
