<?php

namespace FloverartBundle\Repository;

use FloverartBundle\Entity\Clients;
use FloverartBundle\Entity\Ship;

/**
 * ShipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param         $id
     * @param Clients $clients
     *
     * @return null|Ship
     */
    public function getShipById($id, Clients $clients)
    {

        $result = $this->getShipByIds([$id], $clients);

        if ($result) {
            return $result[0];
        }

        return null;
    }

    /**
     * @param array   $ids
     * @param Clients $clients
     *
     * @return array
     */
    public function getShipByIds(array $ids, Clients $clients)
    {
        $r = $this->findBy([
            'id'       => $ids,
            'clientId' => $clients->getId()
        ]);

        $result = [];
        foreach ($r as $item) {
            $result[$item->getId()] = $item;
        }

        return $result;
    }

    /**
     * @param array   $ids
     *
     * @return array
     */
    public function getShipByOnlyIds(array $ids)
    {
        $r = $this->findBy(['id'=> $ids]);

        $result = [];
        foreach ($r as $item) {
            $result[$item->getId()] = $item;
        }

        return $result;
    }
}
