<?php

namespace FloverartBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersQuery( array $filter = [])
    {
        $q = $this->createQueryBuilder("p")
            ->andWhere('p.isDeleted = 0')
            ->orderBy('p.id','DESC');

        return $q;
    }

    /**
     * @param $login
     * @param $password
     *
     * @return null|object
     */
    public function getAuthUser($login, $password)
    {
        $criteria = [
            'login' => $login,
        ];

        $user = $this->findOneBy($criteria);

        if (!$user || !$user->isCorrectPassword($password))
            return null;

        return $user;
    }
}
