<?php

namespace FloverartBundle\Repository;

/**
 * UserPermissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPermissionsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return array
     */
    public function getListPermissions($id)
    {
        $res = $this->findBy(['userId' => (int)$id]);

        $result =[];
        foreach ($res as $item)
        {
            $result[] = $item->getField();
        }

        return $result;
    }
}
