<?php

namespace FloverartBundle\Repository;

/**
 * UserPermissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPermissionsRepository extends \Doctrine\ORM\EntityRepository
{
}
